# Generated by Django 4.2.23 on 2025-06-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=255, verbose_name="Фамилия Имя Отчество"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Контактный номер телефона",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Сообщение / Комментарий к звонку",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("question", "Задать вопрос"),
                            ("callback", "Обратный звонок"),
                        ],
                        max_length=50,
                        verbose_name="Тип запроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Запрос обратной связи",
                "verbose_name_plural": "Запросы обратной связи",
                "ordering": ["-created_at"],
            },
        ),
    ]
