# Generated by Django 4.2.23 on 2025-06-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок страницы"),
                ),
                ("content", models.TextField(verbose_name="Содержимое страницы")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about_us/",
                        verbose_name="Изображение для страницы",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница 'О компании'",
                "verbose_name_plural": "Страница 'О компании'",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "phone_number_main",
                    models.CharField(
                        max_length=20, verbose_name="Основной номер телефона"
                    ),
                ),
                (
                    "phone_number_alt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Дополнительный номер телефона",
                    ),
                ),
                (
                    "email_main",
                    models.EmailField(max_length=254, verbose_name="Основной Email"),
                ),
                (
                    "email_alt",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Дополнительный Email",
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        help_text="ПН-ПТ 9:00-18:00",
                        max_length=255,
                        verbose_name="Часы работы",
                    ),
                ),
                (
                    "map_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на карту (Google Maps/Yandex Maps)",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Facebook"
                    ),
                ),
                (
                    "instagram_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Instagram"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактная информация",
                "verbose_name_plural": "Контактная информация",
            },
        ),
    ]
