# Generated by Django 4.2.23 on 2025-06-28 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutuspage_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная запись'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='Медицинская Клиника', max_length=200, verbose_name='Название клиники'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание/Миссия'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
