# Generated by Django 4.2.23 on 2025-06-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_contactinfo_options_contactinfo_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Полное имя"),
                ),
                (
                    "specialty",
                    models.CharField(max_length=100, verbose_name="Специализация"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="Опыт работы (лет)"),
                ),
                ("education", models.TextField(blank=True, verbose_name="Образование")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный врач"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
                "ordering": ["full_name"],
            },
        ),
    ]
