# Generated by Django 4.2.23 on 2025-06-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-псевдоним, генерируется автоматически из названия.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше категория в списке.",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория услуги",
                "verbose_name_plural": "Категории услуг",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-псевдоним, генерируется автоматически из названия.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Короткое описание услуги, до 200 символов.",
                        verbose_name="Краткое описание (для списка)",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        verbose_name="Полное описание (для детальной страницы)"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Оставьте пустым, если цена варьируется (см. пункты прайс-листа).",
                        max_digits=10,
                        null=True,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="service_images/",
                        verbose_name="Изображение услуги",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="core.servicecategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="services",
                        to="core.doctor",
                        verbose_name="Врачи, предоставляющие услугу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        max_length=200, verbose_name="Наименование пункта прайса"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Единица измерения (например, 'за сеанс')",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_items",
                        to="core.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт прайс-листа услуги",
                "verbose_name_plural": "Пункты прайс-листа услуг",
                "ordering": ["order", "item_name"],
                "unique_together": {("service", "item_name")},
            },
        ),
    ]
