# Generated by Django 4.2.23 on 2025-07-01 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_doctor_default_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='default_interval_minutes',
            field=models.IntegerField(default=30, help_text='Используется для генерации слотов для записи по умолчанию. Минимум 5 минут.', verbose_name='Стандартный интервал приема (мин)'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа/анализа')),
                ('file', models.FileField(help_text='Загрузите файл с результатами анализов или медицинским заключением (PDF, JPG, DOCX и т.д.).', upload_to='medical_records/', verbose_name='Файл (анализ, заключение)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Дополнительные примечания')),
                ('appointment', models.OneToOneField(help_text='Медицинская запись привязана к конкретному приему.', on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.appointment', verbose_name='Запись на прием')),
                ('uploaded_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Загружено врачом')),
            ],
            options={
                'verbose_name': 'Медицинская запись/Результат',
                'verbose_name_plural': 'Медицинские записи/Результаты',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
