upstream django {
    # web - это имя твоего сервиса Django в docker-compose.yml
    # 8000 - это порт, на котором Django запущен внутри контейнера web
    server web:8000;
}

server {
    listen 80; # Nginx будет слушать порт 80

    # Заголовки для правильной работы проксирования
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    # Обслуживание статических файлов Django
    location /static/ {
        # Путь к статическим файлам внутри контейнера web
        # Это та директория, куда collectstatic собирает файлы
        alias /app/static_collected/;
        expires 30d; # Кэшировать статику на 30 дней
        add_header Cache-Control "public, no-transform";
    }

    # Обслуживание медиафайлов Django
    location /media/ {
        # Путь к медиафайлам внутри контейнера web
        alias /app/media/;
        expires 30d; # Кэшировать медиа на 30 дней
        add_header Cache-Control "public, no-transform";
    }

    # Перенаправление всех остальных запросов на Django (через Gunicorn/WSGI)
    location / {
        try_files $uri @django;
    }

    location @django {
        proxy_pass http://django;
    }
}